version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bevin-crud"
s3_bucket = "bevinbucket1"
s3_prefix = "bevin-crud"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "StageName=\"Dev\""
disable_rollback = true
